version: '3.9'
services:
  nginx:
    image: '${NGINX_IMAGE}'
    container_name: '${NGINX_CONTAINER_NAME}'
    hostname: '${NGINX_HOSTNAME}'
    restart: always
    environment:
      TZ: '${TZ}'
    volumes:
      - ./src/conf.d:/etc/nginx/conf.d
      - ./src/data/:/etc/nginx/data
      - ./src/nginx.conf:/etc/nginx/nginx.conf
      - ./src/default.conf:/etc/nginx/default.conf
      - ./var/cache/:/etc/nginx/cache/
      - ./var/log/:/var/log/nginx/
    ports:
      - '${NGINX_SERVER_HTTP_PORT:-80}:80'
      - '${NGINX_SERVER_HTTPS_PORT:-443}:443'

  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: "${POSTGRES_CONTAINER_NAME}"
    hostname: "${POSTGRES_HOSTNAME}"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: '${POSTGRES_DATABASE}'
      PGPASSWORD: '${POSTGRES_PASSWORD:-secret}'
      TZ: "${TZ}"
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${POSTGRES_DATABASE}",
          "-U",
          "${POSTGRES_USER}"
        ]
      retries: 3
      timeout: 5s

  minio:
    image: "${MINIO_IMAGE}"
    container_name: "${MINIO_CONTAINER_NAME}"
    hostname: "${MINIO_HOSTNAME_NAME}"
    environment:
      TZ: '${TZ}'
      MINIO_BROWSER_REDIRECT_URL: https://minio.codespaces.ir/
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./storage/minio:/data/minio
    command: minio server /data/minio --console-address ":80"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:9000/minio/health/live"
        ]
      retries: 3
      timeout: 5s

  pgadmin:
    image: "${PGADMIN_IMAGE}"
    container_name: "${PGADMIN_CONTAINER_NAME}"
    hostname: "${PGADMIN_HOSTNAME}"
    restart: unless-stopped
    environment:
      TZ: '${TZ}'
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - ./storage/pgadmin:/var/lib/pgadmin

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./storage/rabbitmq/data/:/var/lib/rabbitmq/
      - ./var/log/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${POSTGRES_USER:-user}
      RABBITMQ_DEFAULT_PASS: ${POSTGRES_USER:-pass}

networks:
  default:
    external: true
    name: '${APP_DOCKER_NETWORK}'
